export const INCREMENT = 'INCREMENT'
export const TOGGLE_DRAWER = 'TOGGLE_DRAWER'
export const TOGGLE_DIALOG = 'TOGGLE_DIALOG'
export const SET_APP_BAR_TITLE = 'SET_APP_BAR_TITLE'
export const _DDMENU = '_DDMENU'
export const _DATA = '_DATA'
export const SERT_CONTROL = 'SERT_CONTROL'